import fs from 'fs';
const path = 'C:/Users/EMOTIVA1/Desktop/vibeloop/apps/mobile/lib/features/chat/presentation/chat_screen.dart';
let text = fs.readFileSync(path, 'utf8');
const start = '        appBar: AppBar(';
const end = '        body: StreamBuilder<List<AnonymousMessageModel>>(';
const s = text.indexOf(start);
const e = text.indexOf(end);
if (s < 0 || e < 0) throw new Error('anchors not found');
let replacement = [
  '        appBar: AppBar(',
  '          backgroundColor: Colors.transparent,',
  '          surfaceTintColor: Colors.transparent,',
  '          elevation: 0,',
  '          toolbarHeight: 106,',
  '          leadingWidth: 66,',
  '          titleSpacing: 0,',
  '          leading: Builder(',
  '            builder: (context) {',
  '              final isDark = Theme.of(context).brightness == Brightness.dark;',
  '              final btnBg = isDark ? const Color(0xFF14192A).withValues(alpha: 0.92) : Colors.white.withValues(alpha: 0.94);',
  '              final btnBorder = isDark ? const Color(0xFF2B3550) : const Color(0xFFE7E9F1);',
  '              return Padding(',
  '                padding: const EdgeInsets.only(left: 12),',
  '                child: Material(',
  '                  color: Colors.transparent,',
  '                  shape: const CircleBorder(),',
  '                  child: Ink(',
  '                    decoration: BoxDecoration(',
  '                      color: btnBg,',
  '                      shape: BoxShape.circle,',
  '                      border: Border.all(color: btnBorder, width: 1),',
  '                      boxShadow: [',
  '                        BoxShadow(',
  '                          color: Colors.black.withValues(alpha: isDark ? 0.28 : 0.10),',
  '                          blurRadius: 14,',
  '                          offset: const Offset(0, 6),',
  '                        ),',
  '                      ],',
  '                    ),',
  '                    child: IconButton(',
  '                      tooltip: \'Volver\',',
  '                      onPressed: () => context.pop(),',
  '                      icon: VibeSvgIcon(',
  '                        VibeAssetIcons.arrowBack,',
  '                        size: 20,',
  '                        color: isDark ? const Color(0xFFD7DDF0) : colorScheme.onSurface,',
  '                      ),',
  '                    ),',
  '                  ),',
  '                ),',
  '              );',
  '            },',
  '          ),',
  '          title: FutureBuilder<GroupModel>(',
  '            future: _groupFuture,',
  '            builder: (context, snapshot) {',
  '              final groupName = snapshot.data?.name ?? \'Grupo __GROUPID__\';',
  '              final memberCount = snapshot.data?.memberCount;',
  '              final memberLabel = memberCount == null',
  '                  ? \'Miembros\'',
  '                  : memberCount == 1',
  '                      ? \'1 miembro\'',
  '                      : \'$memberCount miembros\';',
  '',
  '              return Padding(',
  '                padding: const EdgeInsets.only(top: 2),',
  '                child: Column(',
  '                  crossAxisAlignment: CrossAxisAlignment.start,',
  '                  mainAxisSize: MainAxisSize.min,',
  '                  children: [',
  '                    Text(',
  '                      groupName,',
  '                      maxLines: 1,',
  '                      overflow: TextOverflow.ellipsis,',
  '                      style: Theme.of(context).textTheme.titleLarge?.copyWith(',
  '                            fontWeight: FontWeight.w800,',
  '                            fontSize: 19,',
  '                            letterSpacing: -0.3,',
  '                          ),',
  '                    ),',
  '                    const SizedBox(height: 6),',
  '                    Text(',
  '                      \'$memberLabel • Privado\'',
  '                      style: Theme.of(context).textTheme.bodyMedium?.copyWith(',
  '                            color: colorScheme.onSurfaceVariant,',
  '                            fontSize: 12.5,',
  '                            fontWeight: FontWeight.w500,',
  '                          ),',
  '                    ),',
  '                  ],',
  '                ),',
  '              );',
  '            },',
  '          ),',
  '          actions: [',
  '            Padding(',
  '              padding: const EdgeInsets.only(right: 12),',
  '              child: Row(',
  '                mainAxisSize: MainAxisSize.min,',
  '                children: [',
  '                  _HeaderActionTile(',
  '                    label: \'Pantallazo\'',
  '                    iconAsset: VibeAssetIcons.screenshot,',
  '                    color: VibeColors.primaryViolet,',
  '                    onTap: _shareChatScreenshot,',
  '                    compact: true,',
  '                  ),',
  '                  const SizedBox(width: 10),',
  '                  _HeaderActionTile(',
  '                    label: \'Invitar\'',
  '                    iconAsset: VibeAssetIcons.invite,',
  '                    color: VibeColors.successGreen,',
  '                    onTap: _shareInviteLink,',
  '                    compact: true,',
  '                  ),',
  '                  const SizedBox(width: 10),',
  '                  _HeaderActionTile(',
  '                    label: \'Link web\'',
  '                    iconAsset: VibeAssetIcons.share,',
  '                    color: VibeColors.coralPink,',
  '                    onTap: _shareWebInviteLink,',
  '                    compact: true,',
  '                  ),',
  '                  const SizedBox(width: 10),',
  '                  _HeaderActionTile(',
  '                    label: \'Fotos\'',
  '                    iconAsset: VibeAssetIcons.photos,',
  '                    color: VibeColors.electricBlue,',
  '                    onTap: () => context.push(\'/groups/__GROUPID__/photos\'),',
  '                    compact: true,',
  '                  ),',
  '                ],',
  '              ),',
  '            ),',
  '          ],',
  '        ),',
  '        body: StreamBuilder<List<AnonymousMessageModel>>('
].join('\n');
replacement = replacement.replaceAll('__GROUPID__', '\${widget.groupId.substring(0, 6)}');
text = text.slice(0, s) + replacement + text.slice(e);
fs.writeFileSync(path, text, 'utf8');