// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVMVxJYks4EYjgOA1qyFx3MxvE8s6ZJk',
    appId: '1:620834239326:android:98347ab2adf8587e3e95cf',
    messagingSenderId: '620834239326',
    projectId: 'vibeloop-84fe4',
    storageBucket: 'vibeloop-84fe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMUwKPPzhjGmASr2uC3OHQpiUAg6OHfh4',
    appId: '1:620834239326:ios:400d3197196555783e95cf',
    messagingSenderId: '620834239326',
    projectId: 'vibeloop-84fe4',
    storageBucket: 'vibeloop-84fe4.firebasestorage.app',
    iosBundleId: 'com.vibeloop.vibeloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMUwKPPzhjGmASr2uC3OHQpiUAg6OHfh4',
    appId: '1:620834239326:ios:400d3197196555783e95cf',
    messagingSenderId: '620834239326',
    projectId: 'vibeloop-84fe4',
    storageBucket: 'vibeloop-84fe4.firebasestorage.app',
    iosBundleId: 'com.vibeloop.vibeloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRhbMk9DO8F3bWOUa5DUikzkxjLFMbHQo',
    appId: '1:620834239326:web:986b04cd6002751a3e95cf',
    messagingSenderId: '620834239326',
    projectId: 'vibeloop-84fe4',
    authDomain: 'vibeloop-84fe4.firebaseapp.com',
    storageBucket: 'vibeloop-84fe4.firebasestorage.app',
    measurementId: 'G-CNBWV5W0FN',
  );
}
